// test_assertions.cpp
//
// Lightweight, dependency-free assertion runner (no gtest, to keep the
// dependency list short) that checks one media-core JSON report at a time
// against known ground truth for a named fixture type. Invoked once per
// fixture, so adding a third/fourth fixture later never requires changing
// this file's interface -- only adding a new `if (fixture_type == "...")`
// branch with its own checks.
//
// Usage:
//   media-core-tests cfr <report.json> [--target SECONDS] [--fps FPS] [--expected-pts SECONDS]
//   media-core-tests vfr <report.json> [--cov-threshold VALUE]
//
// --target/--fps default to 1.1 / 30.0, matching the fixture generated by
// scripts/generate_fixtures.sh, but are real arguments -- not hardcoded --
// so this binary can be pointed at a differently-timed target or a
// differently-encoded CFR fixture without editing this file.
//
// --expected-pts is for targets deliberately placed near a frame boundary
// (e.g. T=2.4999, one tick before a 2.5s frame edge): near a boundary the
// *correct* selected frame can legitimately be close to a full frame
// interval away from --target itself, so the default "within half a frame
// of --target" check would incorrectly fail a correct implementation.
// --expected-pts instead checks the selected frame's PTS against a known
// exact answer. Example: for the CFR fixture (30fps, frame interval
// exactly 1/30s), T=2.4999 should select the frame at PTS 2.466667s (the
// last frame at or before the target), so:
//   media-core-tests cfr report.json --target 2.4999 --expected-pts 2.466667
//
// Typical run (two invocations, one per required fixture):
//   ./scripts/generate_fixtures.sh
//   ./build/media-core fixtures/cfr_bframes.mp4 \
//       --targets 0.0,0.5,1.1,2.4999 --output /tmp/cfr_report.json
//   ./build/media-core fixtures/vfr_known_pts.mp4 \
//       --targets 0.2,0.75,1.9 --output /tmp/vfr_report.json
//   ./build/media-core-tests cfr /tmp/cfr_report.json --target 1.1 --fps 30
//   ./build/media-core-tests cfr /tmp/cfr_report.json --target 2.4999 --expected-pts 2.466667
//   ./build/media-core-tests vfr /tmp/vfr_report.json
//
// This intentionally reads the JSON *report* rather than re-implementing
// decode logic, so it is testing exactly the artifact a downstream consumer
// (the JSON report) would see.
//
// WHY TWO DIFFERENT FIXTURE TYPES EXIST AT ALL: a bug that only manifests
// on variable-frame-rate content (e.g. the CFR/VFR classifier always
// returning "CFR" regardless of input) would be invisible if this suite
// only ever ran against the CFR fixture -- that fixture is *supposed* to
// report CFR, so a broken always-CFR classifier would pass by accident.
// The VFR fixture and CFR fixture each exist to catch a different class of
// bug; neither is redundant with the other.
#include <cmath>
#include <cstdlib>
#include <fstream>
#include <iostream>
#include <optional>
#include <sstream>
#include <string>

#include "json.hpp"

using json = nlohmann::json;

namespace {

int g_failures = 0;
int g_checks = 0;

void check(bool condition, const std::string& description) {
    g_checks++;
    if (!condition) {
        g_failures++;
        std::cerr << "FAIL: " << description << "\n";
    } else {
        std::cout << "PASS: " << description << "\n";
    }
}

// Distinct from check(): reports an informational skip rather than a
// pass/fail, for cases where the requested check genuinely doesn't apply
// (e.g. a target that fell outside the file's duration and was legitimately
// clamped, rather than being a bug).
void skip(const std::string& description) {
    std::cout << "SKIP: " << description << "\n";
}

json loadReport(const std::string& path) {
    std::ifstream f(path);
    if (!f) {
        std::cerr << "Could not open report file: " << path << "\n";
        std::exit(2);
    }
    json j;
    f >> j;
    return j;
}

// Half a frame interval at the fixture's known frame rate is our tolerance:
// a correct implementation should land within this of the true PTS. This is
// the "plausible timestamp bug" tolerance referenced in the assessment.
double halfFrameTolerance(double fps) { return 0.5 / fps; }

// Parses a rational string like "30/1" (as written by json_report.cpp for
// avg_frame_rate/r_frame_rate) into a double. Returns nullopt if the field
// is null or malformed, rather than throwing -- callers decide how to
// treat a missing value.
std::optional<double> parseRationalString(const json& value) {
    if (value.is_null()) return std::nullopt;
    std::string s = value.get<std::string>();
    size_t slash = s.find('/');
    if (slash == std::string::npos) return std::nullopt;
    try {
        double num = std::stod(s.substr(0, slash));
        double den = std::stod(s.substr(slash + 1));
        if (den == 0.0) return std::nullopt;
        return num / den;
    } catch (const std::exception&) {
        return std::nullopt;
    }
}

// ---------------------------------------------------------------------------
// CLI argument parsing and validation
// ---------------------------------------------------------------------------

struct CfrArgs {
    double target_s = 1.1;
    double fps = 30.0;
    std::optional<double> expected_pts_s;  // see --expected-pts below
};

// Parses --target/--fps/--expected-pts out of argv, validates them, and
// exits(2) with a clear message on any parse failure or out-of-range value
// rather than silently falling back to a default or producing a
// nonsensical tolerance (e.g. a negative or zero fps would make
// halfFrameTolerance() meaningless).
CfrArgs parseCfrArgs(int argc, char** argv, int start_index) {
    CfrArgs args;
    for (int i = start_index; i < argc; ++i) {
        std::string flag = argv[i];
        auto needValue = [&](const char* name) -> std::string {
            if (i + 1 >= argc) {
                std::cerr << "error: missing value for " << name << "\n";
                std::exit(2);
            }
            return argv[++i];
        };

        if (flag == "--target") {
            std::string val = needValue("--target");
            try {
                size_t pos = 0;
                args.target_s = std::stod(val, &pos);
                if (pos != val.size()) throw std::invalid_argument("trailing characters");
            } catch (const std::exception&) {
                std::cerr << "error: --target '" << val << "' is not a valid number\n";
                std::exit(2);
            }
            if (!std::isfinite(args.target_s) || args.target_s < 0.0) {
                std::cerr << "error: --target must be a finite, non-negative number of "
                             "seconds (got "
                          << args.target_s << ")\n";
                std::exit(2);
            }
        } else if (flag == "--fps") {
            std::string val = needValue("--fps");
            try {
                size_t pos = 0;
                args.fps = std::stod(val, &pos);
                if (pos != val.size()) throw std::invalid_argument("trailing characters");
            } catch (const std::exception&) {
                std::cerr << "error: --fps '" << val << "' is not a valid number\n";
                std::exit(2);
            }
            if (!std::isfinite(args.fps) || args.fps <= 0.0) {
                std::cerr << "error: --fps must be a finite, positive number (got "
                          << args.fps << ")\n";
                std::exit(2);
            }
        } else if (flag == "--expected-pts") {
            std::string val = needValue("--expected-pts");
            try {
                size_t pos = 0;
                double v = std::stod(val, &pos);
                if (pos != val.size()) throw std::invalid_argument("trailing characters");
                args.expected_pts_s = v;
            } catch (const std::exception&) {
                std::cerr << "error: --expected-pts '" << val << "' is not a valid number\n";
                std::exit(2);
            }
            if (!std::isfinite(*args.expected_pts_s) || *args.expected_pts_s < 0.0) {
                std::cerr << "error: --expected-pts must be a finite, non-negative "
                             "number of seconds\n";
                std::exit(2);
            }
        } else {
            std::cerr << "error: unknown argument '" << flag << "' for 'cfr'\n";
            std::exit(2);
        }
    }
    return args;
}

struct VfrArgs {
    double cov_threshold = 0.02;  // must match MediaInspector's own CFR/VFR threshold
};

VfrArgs parseVfrArgs(int argc, char** argv, int start_index) {
    VfrArgs args;
    for (int i = start_index; i < argc; ++i) {
        std::string flag = argv[i];
        if (flag == "--cov-threshold") {
            if (i + 1 >= argc) {
                std::cerr << "error: missing value for --cov-threshold\n";
                std::exit(2);
            }
            std::string val = argv[++i];
            try {
                size_t pos = 0;
                args.cov_threshold = std::stod(val, &pos);
                if (pos != val.size()) throw std::invalid_argument("trailing characters");
            } catch (const std::exception&) {
                std::cerr << "error: --cov-threshold '" << val << "' is not a valid number\n";
                std::exit(2);
            }
            if (!std::isfinite(args.cov_threshold) || args.cov_threshold <= 0.0) {
                std::cerr << "error: --cov-threshold must be a finite, positive number\n";
                std::exit(2);
            }
        } else {
            std::cerr << "error: unknown argument '" << flag << "' for 'vfr'\n";
            std::exit(2);
        }
    }
    return args;
}

// ---------------------------------------------------------------------------
// Per-fixture-type check sets. Each function only assumes the shape of the
// fixture it's named after; add a new function + dispatch branch to cover
// an additional fixture without touching any existing one.
// ---------------------------------------------------------------------------

// Fixture: cfr_bframes.mp4 by default (30fps, 2 B-frames, GOP size 30 --
// see scripts/generate_fixtures.sh), but target_s/fps are caller-supplied
// so this also works against any other CFR fixture at a different rate.
void checkCfrFixture(const json& report, const CfrArgs& args) {
    const double tol = halfFrameTolerance(args.fps);

    check(report["stream_summary"]["cfr_vfr_verdict"] == "CFR",
          "CFR fixture: verdict is CFR");

    check(!report["frame_requests"].empty(), "CFR fixture: frame_requests present");

    // Necessary check condition: confirm --fps actually matches what the
    // report itself measured, rather than blindly trusting the caller's
    // assumption. If these disagree, the tolerance computed from --fps
    // below would be testing against the wrong frame rate entirely, and
    // every subsequent check in this function would be unreliable.
    std::optional<double> reported_fps =
        parseRationalString(report["stream_summary"]["avg_frame_rate"]);
    if (reported_fps.has_value()) {
        check(std::abs(*reported_fps - args.fps) < 0.01,
              "CFR fixture: --fps (" + std::to_string(args.fps) +
                  ") matches report's own avg_frame_rate (" +
                  std::to_string(*reported_fps) + ")");
    } else {
        skip("CFR fixture: --fps cross-check (report has no avg_frame_rate to compare "
             "against)");
    }

    // Necessary check condition: confirm --target actually falls within
    // the file's reported duration. A target beyond EOF or before the
    // start is expected to hit the clamped_to_first_frame/
    // clamped_to_last_frame fallback path (tested separately, and
    // correctly, in EVIDENCE.md's frame-request table) -- it is not a bug
    // for such a target to land far from the requested time, so the strict
    // half-frame tolerance check below would be the wrong check to apply
    // and must be skipped rather than run and misreported as a failure.
    double duration_s = report["stream_summary"]["duration_s"].get<double>();
    bool target_in_range = (args.target_s >= 0.0) && (args.target_s <= duration_s);

    // Assertion: seeking to --target should select a frame at the correct
    // PTS. Two modes, because "correct" means different things depending
    // on where --target falls relative to a frame boundary:
    //
    //   (a) --expected-pts given (use for targets deliberately placed near
    //       a frame boundary, e.g. T=2.4999 just before a 2.5s frame edge):
    //       the selected frame's PTS must match --expected-pts almost
    //       exactly. Near a boundary, the *correct* answer can legitimately
    //       be close to a full frame interval away from --target itself
    //       (that's the point of testing the boundary), so comparing
    //       against --target with a half-frame tolerance would incorrectly
    //       fail a correct implementation here.
    //
    //   (b) --expected-pts not given (the default, for interior targets
    //       like T=1.1s that aren't near a boundary): the selected PTS must
    //       be within half a frame interval of --target itself. This is
    //       the simpler, more common case and catches a coarse "off by one
    //       keyframe" or "wrong rounding direction" seek/selection bug.
    bool found_target = false;
    for (const auto& r : report["frame_requests"]) {
        if (std::abs(r["target_s"].get<double>() - args.target_s) < 1e-9) {
            found_target = true;
            check(r["found"].get<bool>(),
                  "CFR fixture: T=" + std::to_string(args.target_s) + "s frame found");
            if (!r["found"].get<bool>()) break;

            double selected_pts_s = r["selected_pts_s"].get<double>();
            bool is_clamped = !r["fallback"].is_null();

            if (args.expected_pts_s.has_value()) {
                double err = std::abs(selected_pts_s - *args.expected_pts_s);
                check(err <= tol, "CFR fixture: T=" + std::to_string(args.target_s) +
                                       "s selected_pts_s (" + std::to_string(selected_pts_s) +
                                       "s) matches --expected-pts (" +
                                       std::to_string(*args.expected_pts_s) +
                                       "s) within tolerance (" + std::to_string(tol) + "s)");
            } else if (target_in_range && !is_clamped) {
                double err = std::abs(r["timing_error_s"].get<double>());
                check(err <= tol, "CFR fixture: T=" + std::to_string(args.target_s) +
                                       "s timing_error_s (" + std::to_string(err) +
                                       "s) within half-frame tolerance (" +
                                       std::to_string(tol) + "s) -- pass --expected-pts "
                                       "instead if this --target is deliberately near a "
                                       "frame boundary");
            } else {
                skip("CFR fixture: T=" + std::to_string(args.target_s) +
                     "s half-frame tolerance check (target is outside the file's "
                     "duration or the request was legitimately clamped; strict "
                     "tolerance does not apply to a clamped boundary frame -- pass "
                     "--expected-pts to test a boundary target precisely instead)");
            }
        }
    }
    check(found_target, "CFR fixture: T=" + std::to_string(args.target_s) +
                             "s target was actually requested (pass a --target that "
                             "appears in the report's --targets list, or regenerate "
                             "the report with this --target included)");

    // Assertion: presentation-order frame_trace PTS values must be
    // non-decreasing -- catches a reordering/seek bug where decode-order
    // (DTS-ish) timestamps leak into the presentation-order trace instead
    // of being properly reordered via best_effort_timestamp.
    bool monotonic = true;
    double prev = -1e18;
    for (const auto& f : report["frame_trace"]) {
        double pts = f["pts_s"].get<double>();
        if (pts < prev - 1e-9) {
            monotonic = false;
            break;
        }
        prev = pts;
    }
    check(monotonic, "CFR fixture: frame_trace PTS values are monotonically "
                      "non-decreasing (presentation order)");
}

// Fixture: vfr_known_pts.mp4 -- genuinely variable frame rate (see
// scripts/generate_fixtures.sh and fixtures/vfr_known_pts.ground_truth_pts.txt).
void checkVfrFixture(const json& report, const VfrArgs& args) {
    check(report["stream_summary"]["cfr_vfr_verdict"] == "VFR",
          "VFR fixture: verdict is VFR (catches false-CFR misclassification)");

    // Assertion: for VFR content, mean/stddev frame interval fields must
    // actually reflect variability -- a stddev of ~0 alongside a VFR
    // verdict would indicate the classifier and the reported statistics
    // have drifted out of sync with each other.
    double stddev = report["stream_summary"]["stddev_frame_interval_s"].get<double>();
    double mean = report["stream_summary"]["mean_frame_interval_s"].get<double>();
    check(mean > 0.0, "VFR fixture: mean_frame_interval_s is positive");
    check(stddev / std::max(mean, 1e-9) > args.cov_threshold,
          "VFR fixture: coefficient of variation exceeds the CFR/VFR "
          "threshold (" + std::to_string(args.cov_threshold) +
          ") used to classify it (internal consistency check)");
}

}  // namespace

int main(int argc, char** argv) {
    if (argc < 3) {
        std::cerr << "Usage: " << argv[0]
                  << " cfr <report.json> [--target SECONDS] [--fps FPS] "
                     "[--expected-pts SECONDS]\n"
                  << "       " << argv[0] << " vfr <report.json> [--cov-threshold VALUE]\n";
        return 2;
    }

    std::string fixture_type = argv[1];
    json report = loadReport(argv[2]);

    if (fixture_type == "cfr") {
        CfrArgs args = parseCfrArgs(argc, argv, 3);
        checkCfrFixture(report, args);
    } else if (fixture_type == "vfr") {
        VfrArgs args = parseVfrArgs(argc, argv, 3);
        checkVfrFixture(report, args);
    } else {
        std::cerr << "Unknown fixture type '" << fixture_type
                  << "'; expected 'cfr' or 'vfr'\n";
        return 2;
    }

    std::cout << "\n" << (g_checks - g_failures) << "/" << g_checks << " checks passed\n";
    return g_failures == 0 ? 0 : 1;
}
